# Generated by Django 6.0.4 on 2026-04-12 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_publicacao', models.DateField(auto_created=True, auto_now_add=True)),
                ('titulo', models.CharField(max_length=150)),
                ('resumo', models.CharField(max_length=250)),
                ('conteudo', models.TextField()),
                ('imagem_capa', models.ImageField(upload_to='noticias/capas/')),
                ('autor', models.CharField(max_length=30)),
                ('foto_autor', models.ImageField(blank=True, null=True, upload_to='autores/fotos/')),
                ('categoria', models.CharField(choices=[('RH', 'RH'), ('TI', 'TI'), ('Evento', 'Evento'), ('Aviso', 'Aviso')], max_length=6)),
            ],
        ),
    ]
